# Generated by Django 4.1.4 on 2022-12-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
