# Generated by Django 4.1.4 on 2022-12-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0002_alter_camp_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rating",
        ),
    ]
