# Generated by Django 4.1.4 on 2022-12-28 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0003_remove_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
