# Generated by Django 4.1.4 on 2022-12-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0004_camp_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="stars",
        ),
        migrations.AddField(
            model_name="rating",
            name="comment",
            field=models.TextField(default="great!!", max_length=1000),
            preserve_default=False,
        ),
    ]
