# Generated by Django 4.1.4 on 2022-12-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0005_remove_rating_stars_rating_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="booking_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="booking_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
